name: app_data
description: "Awesome Quotes Data Layer"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_core:
    path: ../app_core
  app_domain:
    path: ../app_domain
  dio: ^4.0.6
  equatable: ^2.0.5
  get_it: ^7.2.0
  injectable: ^2.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  test: any
  very_good_analysis: ^3.1.0
