name: app_ui_widgetbooks
description: Widgetbook for App UI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  app_ui:
    path: ../../packages/app_ui
  flutter:
    sdk: flutter
  widgetbook: ^3.0.0-beta.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
