name: quotes_app

packages:
  - apps/**
  - packages/**

scripts:
  upgrade-deps:
    run: melos exec flutter pub upgrade

  upgrade-deps-major-versions:
    run: melos exec flutter pub upgrade --major-versions

  fix:all:
    run: melos exec dart fix --apply
    description: Run dart fix for all packages.
