name: quotes
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancing_script/DancingScript-Regular.ttf
          weight: 400
        - asset: assets/fonts/dancing_script/DancingScript-Medium.ttf
          weight: 500
        - asset: assets/fonts/dancing_script/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dancing_script/DancingScript-Bold.ttf
          weight: 700
