name: app_domain
description: "Awesome Quotes Domain Layer"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_core:
    path: ../../packages/app_core
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^4.0.0+1
