name: flutter_quotable
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  app_core:
    path: ../../packages/app_core
  app_data:
    path: ../../packages/app_data
  app_domain:
    path: ../../packages/app_domain
  app_ui:
    path: ../../packages/app_ui
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
