name: flutter_quotable
description: A new Flutter project.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  app_core:
    path: ../../packages/app_core
  app_data:
    path: ../../packages/app_data
  app_domain:
    path: ../../packages/app_domain
  app_ui:
    path: ../../packages/app_ui
  cupertino_icons: ^1.0.2
  # firebase plugins need to be direct dependencies
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.5.2
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
