include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    flutter_style_todos: false
