name: app_core
description: App Core
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  logger: ^1.1.0
  meta: ^1.8.0

dev_dependencies:
  very_good_analysis: ^3.1.0
