name: app_core
description: App Core
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.1.0
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  logger: ^1.1.0
  meta: ^1.8.0

dev_dependencies:
  very_good_analysis: ^4.0.0+1
