name: app_core
description: App Core
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0
