name: app_ui
description: UI Toolkit for the App Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_core:
    path: ../../packages/app_core
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^3.2.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Caveat
      fonts:
        - asset: assets/fonts/caveat/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/caveat/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/caveat/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/caveat/Caveat-Bold.ttf
          weight: 700
